# Generated by Django 4.2.16 on 2024-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
    ]
